# automatically generated by the FlatBuffers compiler, do not modify
# namespace: AuthorChunk
import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
class Author(object):
    __slots__ = ['_tab']
    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Author()
        x.Init(buf, n + offset)
        return x
    @classmethod
    def GetRootAsAuthor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AuthorBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x43\x48", size_prefixed=size_prefixed)
    # Author
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)
    # Author
    def Author(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None
    # Author
    def PoemCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0
    # Author
    def PoemIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""
    # Author
    def PoemIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0
    # Author
    def PoemIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0
    # Author
    def PoemTypeCounts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from AuthorChunk.WordFreq import WordFreq
            obj = WordFreq()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None
    # Author
    def PoemTypeCountsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0
    # Author
    def PoemTypeCountsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0
    # Author
    def MeterPatterns(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from AuthorChunk.MeterPattern import MeterPattern
            obj = MeterPattern()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None
    # Author
    def MeterPatternsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0
    # Author
    def MeterPatternsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0
    # Author
    def WordFrequency(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from AuthorChunk.WordFreq import WordFreq
            obj = WordFreq()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None
    # Author
    def WordFrequencyLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0
    # Author
    def WordFrequencyIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0
    # Author
    def SimilarAuthors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from AuthorChunk.SimilarAuthor import SimilarAuthor
            obj = SimilarAuthor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None
    # Author
    def SimilarAuthorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0
    # Author
    def SimilarAuthorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0
def AuthorStart(builder):
    builder.StartObject(7)
def Start(builder):
    AuthorStart(builder)
def AuthorAddAuthor(builder, author):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(author), 0)
def AddAuthor(builder, author):
    AuthorAddAuthor(builder, author)
def AuthorAddPoemCount(builder, poemCount):
    builder.PrependInt32Slot(1, poemCount, 0)
def AddPoemCount(builder, poemCount):
    AuthorAddPoemCount(builder, poemCount)
def AuthorAddPoemIds(builder, poemIds):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(poemIds), 0)
def AddPoemIds(builder, poemIds):
    AuthorAddPoemIds(builder, poemIds)
def AuthorStartPoemIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)
def StartPoemIdsVector(builder, numElems):
    return AuthorStartPoemIdsVector(builder, numElems)
def AuthorAddPoemTypeCounts(builder, poemTypeCounts):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(poemTypeCounts), 0)
def AddPoemTypeCounts(builder, poemTypeCounts):
    AuthorAddPoemTypeCounts(builder, poemTypeCounts)
def AuthorStartPoemTypeCountsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)
def StartPoemTypeCountsVector(builder, numElems):
    return AuthorStartPoemTypeCountsVector(builder, numElems)
def AuthorAddMeterPatterns(builder, meterPatterns):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(meterPatterns), 0)
def AddMeterPatterns(builder, meterPatterns):
    AuthorAddMeterPatterns(builder, meterPatterns)
def AuthorStartMeterPatternsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)
def StartMeterPatternsVector(builder, numElems):
    return AuthorStartMeterPatternsVector(builder, numElems)
def AuthorAddWordFrequency(builder, wordFrequency):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(wordFrequency), 0)
def AddWordFrequency(builder, wordFrequency):
    AuthorAddWordFrequency(builder, wordFrequency)
def AuthorStartWordFrequencyVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)
def StartWordFrequencyVector(builder, numElems):
    return AuthorStartWordFrequencyVector(builder, numElems)
def AuthorAddSimilarAuthors(builder, similarAuthors):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(similarAuthors), 0)
def AddSimilarAuthors(builder, similarAuthors):
    AuthorAddSimilarAuthors(builder, similarAuthors)
def AuthorStartSimilarAuthorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)
def StartSimilarAuthorsVector(builder, numElems):
    return AuthorStartSimilarAuthorsVector(builder, numElems)
def AuthorEnd(builder):
    return builder.EndObject()
def End(builder):
    return AuthorEnd(builder)
