# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AuthorChunk

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AuthorChunkFile(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AuthorChunkFile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAuthorChunkFile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AuthorChunkFileBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x43\x48", size_prefixed=size_prefixed)

    # AuthorChunkFile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AuthorChunkFile
    def Authors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from AuthorChunk.Author import Author
            obj = Author()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AuthorChunkFile
    def AuthorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AuthorChunkFile
    def AuthorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # AuthorChunkFile
    def ChunkIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AuthorChunkFile
    def TotalAuthors(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def AuthorChunkFileStart(builder):
    builder.StartObject(3)

def Start(builder):
    AuthorChunkFileStart(builder)

def AuthorChunkFileAddAuthors(builder, authors):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(authors), 0)

def AddAuthors(builder, authors):
    AuthorChunkFileAddAuthors(builder, authors)

def AuthorChunkFileStartAuthorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAuthorsVector(builder, numElems):
    return AuthorChunkFileStartAuthorsVector(builder, numElems)

def AuthorChunkFileAddChunkIndex(builder, chunkIndex):
    builder.PrependInt32Slot(1, chunkIndex, 0)

def AddChunkIndex(builder, chunkIndex):
    AuthorChunkFileAddChunkIndex(builder, chunkIndex)

def AuthorChunkFileAddTotalAuthors(builder, totalAuthors):
    builder.PrependInt32Slot(2, totalAuthors, 0)

def AddTotalAuthors(builder, totalAuthors):
    AuthorChunkFileAddTotalAuthors(builder, totalAuthors)

def AuthorChunkFileEnd(builder):
    return builder.EndObject()

def End(builder):
    return AuthorChunkFileEnd(builder)
