# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AuthorChunk

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MeterPattern(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MeterPattern()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeterPattern(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MeterPatternBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x43\x48", size_prefixed=size_prefixed)

    # MeterPattern
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MeterPattern
    def Pattern(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MeterPattern
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MeterPatternStart(builder):
    builder.StartObject(2)

def Start(builder):
    MeterPatternStart(builder)

def MeterPatternAddPattern(builder, pattern):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pattern), 0)

def AddPattern(builder, pattern):
    MeterPatternAddPattern(builder, pattern)

def MeterPatternAddCount(builder, count):
    builder.PrependInt32Slot(1, count, 0)

def AddCount(builder, count):
    MeterPatternAddCount(builder, count)

def MeterPatternEnd(builder):
    return builder.EndObject()

def End(builder):
    return MeterPatternEnd(builder)
