# automatically generated by the FlatBuffers compiler, do not modify
# namespace: AuthorChunk
import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
class SimilarAuthor(object):
    __slots__ = ['_tab']
    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimilarAuthor()
        x.Init(buf, n + offset)
        return x
    @classmethod
    def GetRootAsSimilarAuthor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SimilarAuthorBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x43\x48", size_prefixed=size_prefixed)
    # SimilarAuthor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)
    # SimilarAuthor
    def Author(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None
    # SimilarAuthor
    def Similarity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0
def SimilarAuthorStart(builder):
    builder.StartObject(2)
def Start(builder):
    SimilarAuthorStart(builder)
def SimilarAuthorAddAuthor(builder, author):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(author), 0)
def AddAuthor(builder, author):
    SimilarAuthorAddAuthor(builder, author)
def SimilarAuthorAddSimilarity(builder, similarity):
    builder.PrependFloat32Slot(1, similarity, 0.0)
def AddSimilarity(builder, similarity):
    SimilarAuthorAddSimilarity(builder, similarity)
def SimilarAuthorEnd(builder):
    return builder.EndObject()
def End(builder):
    return SimilarAuthorEnd(builder)
