# automatically generated by the FlatBuffers compiler, do not modify
# namespace: AuthorChunk
import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
class WordFreq(object):
    __slots__ = ['_tab']
    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WordFreq()
        x.Init(buf, n + offset)
        return x
    @classmethod
    def GetRootAsWordFreq(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WordFreqBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x43\x48", size_prefixed=size_prefixed)
    # WordFreq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)
    # WordFreq
    def Word(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None
    # WordFreq
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0
def WordFreqStart(builder):
    builder.StartObject(2)
def Start(builder):
    WordFreqStart(builder)
def WordFreqAddWord(builder, word):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(word), 0)
def AddWord(builder, word):
    WordFreqAddWord(builder, word)
def WordFreqAddCount(builder, count):
    builder.PrependInt32Slot(1, count, 0)
def AddCount(builder, count):
    WordFreqAddCount(builder, count)
def WordFreqEnd(builder):
    return builder.EndObject()
def End(builder):
    return WordFreqEnd(builder)
