# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WordSimilarity

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SimilarWord(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimilarWord()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSimilarWord(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SimilarWordBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x57\x52\x53\x56", size_prefixed=size_prefixed)

    # SimilarWord
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimilarWord
    def WordId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SimilarWord
    def Similarity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def SimilarWordStart(builder):
    builder.StartObject(2)

def Start(builder):
    SimilarWordStart(builder)

def SimilarWordAddWordId(builder, wordId):
    builder.PrependInt32Slot(0, wordId, 0)

def AddWordId(builder, wordId):
    SimilarWordAddWordId(builder, wordId)

def SimilarWordAddSimilarity(builder, similarity):
    builder.PrependInt32Slot(1, similarity, 0)

def AddSimilarity(builder, similarity):
    SimilarWordAddSimilarity(builder, similarity)

def SimilarWordEnd(builder):
    return builder.EndObject()

def End(builder):
    return SimilarWordEnd(builder)
