# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WordSimilarity

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WordEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WordEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWordEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WordEntryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x57\x52\x53\x56", size_prefixed=size_prefixed)

    # WordEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WordEntry
    def WordId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WordEntry
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WordEntry
    def SimilarWords(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from WordSimilarity.SimilarWord import SimilarWord
            obj = SimilarWord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WordEntry
    def SimilarWordsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WordEntry
    def SimilarWordsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def WordEntryStart(builder):
    builder.StartObject(3)

def Start(builder):
    WordEntryStart(builder)

def WordEntryAddWordId(builder, wordId):
    builder.PrependInt32Slot(0, wordId, 0)

def AddWordId(builder, wordId):
    WordEntryAddWordId(builder, wordId)

def WordEntryAddFrequency(builder, frequency):
    builder.PrependInt32Slot(1, frequency, 0)

def AddFrequency(builder, frequency):
    WordEntryAddFrequency(builder, frequency)

def WordEntryAddSimilarWords(builder, similarWords):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(similarWords), 0)

def AddSimilarWords(builder, similarWords):
    WordEntryAddSimilarWords(builder, similarWords)

def WordEntryStartSimilarWordsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSimilarWordsVector(builder, numElems):
    return WordEntryStartSimilarWordsVector(builder, numElems)

def WordEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return WordEntryEnd(builder)
