# automatically generated by the FlatBuffers compiler, do not modify
# namespace: WordSimilarity
import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
class WordSimilarityFile(object):
    __slots__ = ['_tab']
    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WordSimilarityFile()
        x.Init(buf, n + offset)
        return x
    @classmethod
    def GetRootAsWordSimilarityFile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WordSimilarityFileBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x57\x52\x53\x56", size_prefixed=size_prefixed)
    # WordSimilarityFile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)
    # WordSimilarityFile
    def Words(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from WordSimilarity.WordEntry import WordEntry
            obj = WordEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None
    # WordSimilarityFile
    def WordsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0
    # WordSimilarityFile
    def WordsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0
    # WordSimilarityFile
    def Vocab(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""
    # WordSimilarityFile
    def VocabLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0
    # WordSimilarityFile
    def VocabIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0
def WordSimilarityFileStart(builder):
    builder.StartObject(2)
def Start(builder):
    WordSimilarityFileStart(builder)
def WordSimilarityFileAddWords(builder, words):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(words), 0)
def AddWords(builder, words):
    WordSimilarityFileAddWords(builder, words)
def WordSimilarityFileStartWordsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)
def StartWordsVector(builder, numElems):
    return WordSimilarityFileStartWordsVector(builder, numElems)
def WordSimilarityFileAddVocab(builder, vocab):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(vocab), 0)
def AddVocab(builder, vocab):
    WordSimilarityFileAddVocab(builder, vocab)
def WordSimilarityFileStartVocabVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)
def StartVocabVector(builder, numElems):
    return WordSimilarityFileStartVocabVector(builder, numElems)
def WordSimilarityFileEnd(builder):
    return builder.EndObject()
def End(builder):
    return WordSimilarityFileEnd(builder)
